baseURL = "https://dennisdel.com/"
languageCode = "en-us"
title = "Den by Default"

builddrafts         = false
canonifyurls        = true
contentdir          = "content"
layoutdir           = "layouts"
publishdir          = "public"
theme               = "cocoa-hugo-theme"
author              = "Den Delimarsky"
pygmentsuseclasses  = true
#disqusShortname     = "den-by-default"
pluralizelisttitles = false
googleAnalytics     = "UA-26345920-1"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"

[params]
latestpostscount       = 5                             # how many posts to display on the home page
i18n_flags             = false                         # whether to display small country flags for available translations
author                 = "Den Delimarsky"
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "Code & Coffee"
email                  = "den@dennisdel.com"
# extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
faviconfile            = "img/leaf.ico"
github                 = "//github.com/dend"
highlightjs            = true
lang                   = "en"
linkedin               = "//linkedin.com/in/dendeli"
noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
selfintro              = ""                            # appears in the site header when set to a non-empty string
twitter                = "//twitter.com/denniscode"
# mastodon               = "//example.com/@you"
# highlightjslanguages = ["go"]                        # additional languages not included in the "common" set
# highlightjsStyle     = "androidstudio"

avatar                 = "images/den.jpeg" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
# gravatar             = "ddelimarsky@live.com"                # do not use in the same time as avatar

    [params.social]
    github = "dend"
    twitter = "DennisCode"
    twitter_domain = "dennisdel.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    instagram = "helloisden"
    linkedin = "dendeli"

    [params.authors]
        [params.authors.Den]

        name			= "Den Delimarsky"
        thumbnail		= "https://dennisdel.com/images/den.jpeg"
        images		= [
                            "https://dennisdel.com/images/postmedia/vancouver-before-holidays/den-tiff-bridge.jpg",
                            "https://dennisdel.com/images/postmedia/vancouver-before-holidays/den-tiff.jpg"
                        ]
        bio			= "Den is an engineer at Microsoft."
        email			= "den@dennisdel.com"

        [params.authors.John.social]
            github			= "dend"
            twitter			= "denniscode"
            instagram		= "helloisden"
            linkedin		= "dendeli"